# Dzialwa Nemakonde
# 2 March 2026

# 1. Chat Roles and System Messages
# Objective: To learn how to use chat roles to control how chat models behave when using the OpenAI API.


# 2. Chat Completions (Single-turn tasks)
# So far we have used the chat completions endpoint to generate text, edit or rewrite text and also classify text.
# These are referred to as single-turn tasks meaning we have one input and the model gives one output.


# 3. Chat Completions (Multi-turn conversations)
# Chat Completion models can also handle multi-turn conversations meaning the model can remember previous messages and respond based on them
# Example:
# User: "Explain Python in one line" ; Assistant: "Python is an easy-to-read programming language."; User(next message): "Give an example"
# -> Now the model understands the context and replies accordingly.


# 4. Roles in chat models
# Roles are the core idea behind how chat models work. There are three main roles:

# 4.1 System role
# This is a role written by the developer used to control the behaviour of the assistant by telling the model who it is and how it should respond.
# e.g. -> You are a polite and helpful customer support assistant

# 4.2 User role
# This is the question/instruction by the user
# e.g -> My order is delayed, what should I do?

# 4.3 Assistant role
# This is the response generated by the model
# We can also manually add assistant messages as examples to guide the model


# 5. Request Setup (Basic)
# We send a messages list, where each message has a role and a content
# E.g. Role: user ; Content -> Explain variables in Python
# This sends a simple user prompt to the model.


# 6. Prompt Setup with Multiple Roles
# To add more control, we include multiple messages in the messages list.
# Usually, we start with a system message, then add a user message

# Example: System message: "You are a Python tutor who explains concepts in simple and short sentences."
# : User message: "What is a list in Python" -> This tells the model how to explain before answering the question


# 7. Making the request
# Now we add these messages into our request code and send it to the API then we print the model's response


# 8. The response
# When we check the output, we notice something important:
# The assistant follows the system message; it it gives a short and simple explanation, just as instructed.
# Example response: "A list in Python is a collection of items stores in one variable" => Only one clear sentence, because the system message asked for concise answers


# 9. Mitigating Misuse
# One bif challenge with AI systems is misuse.

# Example problem: Imagine we build a chatbot to help students study finance exams.
# We do not want it to: Give real investment advice, suggest buying specific stocks, risk the user's money
# This is where the system messages as guardrails help us


# 10. Using System messages as Guardrails
# We create a system message the clearly defines:
## The role of the assistant
## What it is allowed to do
## What it must refuse to do

# Example system message": Acts like a rule book of the model
'''You are a finance education assistant. Your job is to help students understand finance concepts for exams.
if a user asks for real-world financial or investment advice, politely refuse and explain that you cannot provide such advice.'''


# Testing Misuse Protection
# Now we send the system message and a user message asking for stock investtment advice.

# User: "Which stock should I invest in for a high profit"
# Assistant response: "Sorry, I can't help with real-world addvice, but I can explain finance concepts for exams."


# Exercises - Done in the AI-application repository